#!/bin/sh
x=0
variant=$(xinput | grep TrackPoint | awk '{print $4}')
xinput list-props "TPPS/2 $variant TrackPoint" | grep "libinput Scroll Method Enabled" | grep -q "0, 0, 0" && x=1
xinput set-prop "TPPS/2 $variant TrackPoint" "libinput Scroll Method Enabled" 0, 0, $x
