#!/bin/sh
if xinput | grep "TPPS/2 IBM" > /dev/null; then
	variant="TPPS/2 IBM TrackPoint"
else
	variant="TPPS/2 Elan TrackPoint"
fi
x=0
xinput list-props "$variant" | grep "libinput Scroll Method Enabled" | grep -q "0, 0, 0" && x=1
xinput set-prop "$variant" "libinput Scroll Method Enabled" 0, 0, $x
